shell = 'zsh'

[plugins]

[plugins.ohmyzsh]
github = 'ohmyzsh/ohmyzsh'
use = ['lib/last-working-dir.zsh', 'themes/gentoo.zsh-theme']


[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.fzf]
inline = '''
case $OSTYPE in
  linux*)  source /usr/share/fzf/key-bindings.zsh ;;
  darwin*) eval "$(fzf --zsh)" ;;
esac
'''

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
